CREATE TABLE IF NOT EXISTS registration (
	id MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	birthday DATE NOT NULL,
	age TINYINT UNSIGNED NOT NULL,
	relationship VARCHAR(20))
	DEFAULT CHARSET=utf8;
	
CREATE TABLE IF NOT EXISTS login (
	id MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
	mailAdress VARCHAR(50) NOT NULL,
	password VARCHAR(20) NOT NULL,
	name VARCHAR(40) NOT NULL,
	birthday DATE NOT NULL,
	age TINYINT UNSIGNED NOT NULL)
	DEFAULT CHARSET=utf8;