CREATE TABLE IF NOT EXISTS registration (
	id MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	birthday DATE NOT NULL,
	age TINYINT UNSIGNED NOT NULL,
	relationship VARCHAR(20))
	DEFAULT CHARSET=utf8;